server:
    port: 8080
    shutdown: graceful
    tomcat:
        # this is default value for tomcat and could be increased
        max-connections: 8192
spring:
    application:
        name: bill-payment
    datasource:
        url: jdbc:h2:mem:billpayment;DB_CLOSE_ON_EXIT=FALSE;INIT=CREATE SCHEMA IF NOT EXISTS billpayment
        username: sa
        password: sa
        driver-class-name: org.h2.Driver

    jpa:
        show-sql: true
        hibernate:
            ddl-auto: update

        database-platform: org.hibernate.dialect.H2Dialect
        defer-datasource-initialization: true
        properties:
            dialect: org.hibernate.dialect.H2Dialect
        generate-ddl: true
        open-in-view: off

    h2:
        console:
            enabled: true
    sql:
        init:
            mode: always
            data-locations: classpath:data.sql

management:
    endpoints:
        web:
            exposure:
                include: '*'

resilience4j:
    retry:
        instances:
            getExchangeRate:
                maxRetryAttempts: 3
                waitDuration: 1s
                enableExponentialBackoff: true
                exponentialBackoffMultiplier: 2

#debug: true
application:
    jwt:
        secret: username